// Generated by gencpp from file ros_ran_num_msg/rand_num.msg
// DO NOT EDIT!


#ifndef ROS_RAN_NUM_MSG_MESSAGE_RAND_NUM_H
#define ROS_RAN_NUM_MSG_MESSAGE_RAND_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_ran_num_msg
{
template <class ContainerAllocator>
struct rand_num_
{
  typedef rand_num_<ContainerAllocator> Type;

  rand_num_()
    : number1(0)
    , number2(0)  {
    }
  rand_num_(const ContainerAllocator& _alloc)
    : number1(0)
    , number2(0)  {
  (void)_alloc;
    }



   typedef uint32_t _number1_type;
  _number1_type number1;

   typedef uint32_t _number2_type;
  _number2_type number2;




  typedef boost::shared_ptr< ::ros_ran_num_msg::rand_num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_ran_num_msg::rand_num_<ContainerAllocator> const> ConstPtr;

}; // struct rand_num_

typedef ::ros_ran_num_msg::rand_num_<std::allocator<void> > rand_num;

typedef boost::shared_ptr< ::ros_ran_num_msg::rand_num > rand_numPtr;
typedef boost::shared_ptr< ::ros_ran_num_msg::rand_num const> rand_numConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_ran_num_msg::rand_num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_ran_num_msg::rand_num_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_ran_num_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ros_ran_num_msg': ['/home/ubuntu/bmw_ros_multiplicator/ROS_Example/src/ros_ran_num_msg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_ran_num_msg::rand_num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_ran_num_msg::rand_num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_ran_num_msg::rand_num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_ran_num_msg::rand_num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_ran_num_msg::rand_num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_ran_num_msg::rand_num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_ran_num_msg::rand_num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "20e27c3e6eee8dfccd76499464b39a05";
  }

  static const char* value(const ::ros_ran_num_msg::rand_num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x20e27c3e6eee8dfcULL;
  static const uint64_t static_value2 = 0xcd76499464b39a05ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_ran_num_msg::rand_num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_ran_num_msg/rand_num";
  }

  static const char* value(const ::ros_ran_num_msg::rand_num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_ran_num_msg::rand_num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 number1\n\
uint32 number2\n\
\n\
";
  }

  static const char* value(const ::ros_ran_num_msg::rand_num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_ran_num_msg::rand_num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number1);
      stream.next(m.number2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rand_num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_ran_num_msg::rand_num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_ran_num_msg::rand_num_<ContainerAllocator>& v)
  {
    s << indent << "number1: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.number1);
    s << indent << "number2: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.number2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_RAN_NUM_MSG_MESSAGE_RAND_NUM_H
